data-back:
   image: busybox:latest
   ports:
     - "2270:22"
   volumes:
     - ./:/var/www/jti-test/
   links:
     - db
   tty: true

fpm:
  build: docker/php
  volumes_from:
    - data-back
  volumes:
    - ./docker/php/:/usr/local/etc/php/
  environment:
    XDEBUG_CONFIG: "remote_host=172.17.0.4 remote_enable=1"
    PHP_IDE_CONFIG: "serverName=Docker"
  expose:
    - 9000
  links:
    - db

nginx:
  image: nginx:latest
  volumes_from:
    - data-back
  ports:
    - "8090:80"
  volumes:
    - ./docker/nginx/:/etc/nginx/conf.d/
  links:
    - fpm

db:
  image: mysql:5.7
  environment:
    MYSQL_DATABASE: jtitest
    MYSQL_USER: test
    MYSQL_PASSWORD: test
    MYSQL_ROOT_PASSWORD: root
  ports:
    - "3306:3306"

phpmyadmin:
  links:
    - db
  image: phpmyadmin/phpmyadmin
  restart: always
  ports:
    - '8080:80'
  environment:
    PMA_HOST: db
    MYSQL_ROOT_PASSWORD: root


